### ISSUE TITLE
Improve Event Resender Logic

### ISSUE THREAD

**Issue by mudaliaraditya** [mudaliaraditya/ChatServer#9]
I have used sleep function for waiting for the next event, what would be better

**Comment by AriesShilz** [comment]
Maybe this will help you: 

**#include <iostream>
#include <chrono>
#include <thread>
 
int main()
{
    using namespace std::chrono_literals;
    std::cout << "Hello. Please wait\n" << std::flush;
    auto start = std::chrono::high_resolution_clock::now();
    std::this_thread::sleep_for(5s);
    auto end = std::chrono::high_resolution_clock::now();
    std::chrono::duration<double, std::milli> elapsed = end-start;
    std::cout << "You  waited " << elapsed.count() << " ms\n";
}**



It blocks the execution of the current thread for minimum the specified sleep_duration. This function may block for longer than sleep_duration due to scheduling or resource contention delays.

Parameter:

sleep_duration: time duration to sleep.

Return Value:

nothing

Exception:

Any exception is thrown by clock, time_point, or duration during the execution.

**Comment by mudaliaraditya** [comment]
thanks will check and test that

**Comment by mudaliaraditya** [comment]
implemented and closed
